// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PawStash.DAL.Context;

#nullable disable

namespace PawStash.DAL.Migrations
{
    [DbContext(typeof(PawStashContext))]
    [Migration("20261002141858_AddDescriptionAndCoverImage")]
    partial class AddDescriptionAndCoverImage
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PawStash.DAL.Entities.FileSystem.FileSystemItem", b =>
                {
                    b.Property<Guid>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.Property<string>("CoverImageMimeType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("cover_image_mime_type");

                    b.Property<string>("CoverImagePath")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("cover_image_path");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("item_type");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("NameLowercase")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name_lowercase")
                        .HasComputedColumnSql("lower(name)", true);

                    b.Property<string>("OwnerEmail")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("owner_email");

                    b.Property<Guid?>("ParentFolderId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_folder_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("ItemId")
                        .HasName("pk_file_system_items");

                    b.HasIndex("ParentFolderId")
                        .HasDatabaseName("ix_file_system_items_parent_folder_id");

                    b.HasIndex("OwnerEmail", "ParentFolderId", "NameLowercase")
                        .IsUnique()
                        .HasDatabaseName("uq_file_system_items_name_in_folder");

                    NpgsqlIndexBuilderExtensions.AreNullsDistinct(b.HasIndex("OwnerEmail", "ParentFolderId", "NameLowercase"), false);

                    b.ToTable("file_system_items", null, t =>
                        {
                            t.HasCheckConstraint("ck_file_system_items_cover_image", "(cover_image_path IS NULL) = (cover_image_mime_type IS NULL)");

                            t.HasCheckConstraint("ck_file_system_items_item_type", "item_type IN ('folder', 'link', 'note', 'photo', 'document')");

                            t.HasCheckConstraint("ck_file_system_items_link_url", "item_type <> 'link' OR link_url IS NOT NULL");

                            t.HasCheckConstraint("ck_file_system_items_note_text", "item_type <> 'note' OR note_text IS NOT NULL");

                            t.HasCheckConstraint("ck_file_system_items_uploaded_file", "item_type NOT IN ('photo', 'document') OR (file_path IS NOT NULL AND file_mime_type IS NOT NULL AND file_size_bytes IS NOT NULL)");
                        });

                    b.HasDiscriminator<string>("ItemType").HasValue("FileSystemItem");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("PawStash.DAL.Entities.User", b =>
                {
                    b.Property<string>("Email")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.HasKey("Email")
                        .HasName("pk_users");

                    b.ToTable("users", (string)null);

                    b.HasData(
                        new
                        {
                            Email = "1979stetsenko@gmail.com"
                        });
                });

            modelBuilder.Entity("PawStash.DAL.Entities.FileSystem.Folder", b =>
                {
                    b.HasBaseType("PawStash.DAL.Entities.FileSystem.FileSystemItem");

                    b.ToTable(t =>
                        {
                            t.HasCheckConstraint("ck_file_system_items_cover_image", "(cover_image_path IS NULL) = (cover_image_mime_type IS NULL)");

                            t.HasCheckConstraint("ck_file_system_items_item_type", "item_type IN ('folder', 'link', 'note', 'photo', 'document')");

                            t.HasCheckConstraint("ck_file_system_items_link_url", "item_type <> 'link' OR link_url IS NOT NULL");

                            t.HasCheckConstraint("ck_file_system_items_note_text", "item_type <> 'note' OR note_text IS NOT NULL");

                            t.HasCheckConstraint("ck_file_system_items_uploaded_file", "item_type NOT IN ('photo', 'document') OR (file_path IS NOT NULL AND file_mime_type IS NOT NULL AND file_size_bytes IS NOT NULL)");
                        });

                    b.HasDiscriminator().HasValue("folder");
                });

            modelBuilder.Entity("PawStash.DAL.Entities.FileSystem.Link", b =>
                {
                    b.HasBaseType("PawStash.DAL.Entities.FileSystem.FileSystemItem");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("link_url");

                    b.ToTable(t =>
                        {
                            t.HasCheckConstraint("ck_file_system_items_cover_image", "(cover_image_path IS NULL) = (cover_image_mime_type IS NULL)");

                            t.HasCheckConstraint("ck_file_system_items_item_type", "item_type IN ('folder', 'link', 'note', 'photo', 'document')");

                            t.HasCheckConstraint("ck_file_system_items_link_url", "item_type <> 'link' OR link_url IS NOT NULL");

                            t.HasCheckConstraint("ck_file_system_items_note_text", "item_type <> 'note' OR note_text IS NOT NULL");

                            t.HasCheckConstraint("ck_file_system_items_uploaded_file", "item_type NOT IN ('photo', 'document') OR (file_path IS NOT NULL AND file_mime_type IS NOT NULL AND file_size_bytes IS NOT NULL)");
                        });

                    b.HasDiscriminator().HasValue("link");
                });

            modelBuilder.Entity("PawStash.DAL.Entities.FileSystem.Note", b =>
                {
                    b.HasBaseType("PawStash.DAL.Entities.FileSystem.FileSystemItem");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("note_text");

                    b.ToTable(t =>
                        {
                            t.HasCheckConstraint("ck_file_system_items_cover_image", "(cover_image_path IS NULL) = (cover_image_mime_type IS NULL)");

                            t.HasCheckConstraint("ck_file_system_items_item_type", "item_type IN ('folder', 'link', 'note', 'photo', 'document')");

                            t.HasCheckConstraint("ck_file_system_items_link_url", "item_type <> 'link' OR link_url IS NOT NULL");

                            t.HasCheckConstraint("ck_file_system_items_note_text", "item_type <> 'note' OR note_text IS NOT NULL");

                            t.HasCheckConstraint("ck_file_system_items_uploaded_file", "item_type NOT IN ('photo', 'document') OR (file_path IS NOT NULL AND file_mime_type IS NOT NULL AND file_size_bytes IS NOT NULL)");
                        });

                    b.HasDiscriminator().HasValue("note");
                });

            modelBuilder.Entity("PawStash.DAL.Entities.FileSystem.UploadedFile", b =>
                {
                    b.HasBaseType("PawStash.DAL.Entities.FileSystem.FileSystemItem");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("file_path");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("file_mime_type");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size_bytes");

                    b.ToTable(t =>
                        {
                            t.HasCheckConstraint("ck_file_system_items_cover_image", "(cover_image_path IS NULL) = (cover_image_mime_type IS NULL)");

                            t.HasCheckConstraint("ck_file_system_items_item_type", "item_type IN ('folder', 'link', 'note', 'photo', 'document')");

                            t.HasCheckConstraint("ck_file_system_items_link_url", "item_type <> 'link' OR link_url IS NOT NULL");

                            t.HasCheckConstraint("ck_file_system_items_note_text", "item_type <> 'note' OR note_text IS NOT NULL");

                            t.HasCheckConstraint("ck_file_system_items_uploaded_file", "item_type NOT IN ('photo', 'document') OR (file_path IS NOT NULL AND file_mime_type IS NOT NULL AND file_size_bytes IS NOT NULL)");
                        });

                    b.HasDiscriminator().HasValue("UploadedFile");
                });

            modelBuilder.Entity("PawStash.DAL.Entities.FileSystem.Document", b =>
                {
                    b.HasBaseType("PawStash.DAL.Entities.FileSystem.UploadedFile");

                    b.ToTable(t =>
                        {
                            t.HasCheckConstraint("ck_file_system_items_cover_image", "(cover_image_path IS NULL) = (cover_image_mime_type IS NULL)");

                            t.HasCheckConstraint("ck_file_system_items_item_type", "item_type IN ('folder', 'link', 'note', 'photo', 'document')");

                            t.HasCheckConstraint("ck_file_system_items_link_url", "item_type <> 'link' OR link_url IS NOT NULL");

                            t.HasCheckConstraint("ck_file_system_items_note_text", "item_type <> 'note' OR note_text IS NOT NULL");

                            t.HasCheckConstraint("ck_file_system_items_uploaded_file", "item_type NOT IN ('photo', 'document') OR (file_path IS NOT NULL AND file_mime_type IS NOT NULL AND file_size_bytes IS NOT NULL)");
                        });

                    b.HasDiscriminator().HasValue("document");
                });

            modelBuilder.Entity("PawStash.DAL.Entities.FileSystem.Photo", b =>
                {
                    b.HasBaseType("PawStash.DAL.Entities.FileSystem.UploadedFile");

                    b.ToTable(t =>
                        {
                            t.HasCheckConstraint("ck_file_system_items_cover_image", "(cover_image_path IS NULL) = (cover_image_mime_type IS NULL)");

                            t.HasCheckConstraint("ck_file_system_items_item_type", "item_type IN ('folder', 'link', 'note', 'photo', 'document')");

                            t.HasCheckConstraint("ck_file_system_items_link_url", "item_type <> 'link' OR link_url IS NOT NULL");

                            t.HasCheckConstraint("ck_file_system_items_note_text", "item_type <> 'note' OR note_text IS NOT NULL");

                            t.HasCheckConstraint("ck_file_system_items_uploaded_file", "item_type NOT IN ('photo', 'document') OR (file_path IS NOT NULL AND file_mime_type IS NOT NULL AND file_size_bytes IS NOT NULL)");
                        });

                    b.HasDiscriminator().HasValue("photo");
                });

            modelBuilder.Entity("PawStash.DAL.Entities.FileSystem.FileSystemItem", b =>
                {
                    b.HasOne("PawStash.DAL.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("OwnerEmail")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_file_system_items_owner");

                    b.HasOne("PawStash.DAL.Entities.FileSystem.Folder", "ParentFolder")
                        .WithMany("Items")
                        .HasForeignKey("ParentFolderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_file_system_items_parent_folder");

                    b.Navigation("ParentFolder");
                });

            modelBuilder.Entity("PawStash.DAL.Entities.FileSystem.Folder", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
